import { ArrowUpRight, Mail, MapPin, Terminal as TerminalIcon } from 'lucide-react'
import { portfolio, projectData } from '../data/portfolio'
export function Home(){return <section id="home" className="section hero"><div className="hero-copy"><p className="eyebrow">Hello, I&apos;m Alex <span>✦</span></p><h1>Ideas into <em>interfaces.</em></h1><p className="lede">I&apos;m a developer who cares about the details — from the first sketch to the final interaction.</p><div className="hero-actions"><a className="button button--primary" href="#projects">Explore my work <ArrowUpRight size={17}/></a><a className="text-link" href="#contact">Let&apos;s talk <span>↗</span></a></div></div><div className="portrait-wrap"><div className="portrait"><div className="portrait-glow"/><div className="portrait-face">A<span>M</span></div></div><div className="portrait-caption"><span>Currently crafting</span><strong>thoughtful digital products</strong></div></div></section>}
export function About(){return <section id="about" className="section split"><div><p className="eyebrow">01 / About</p><h2>A bit about<br/><em>how I work.</em></h2></div><div className="section-body"><p className="big-copy">{portfolio.bio}</p><div className="meta-row"><span><MapPin size={16}/> {portfolio.location}</span><span>UTC +05:30</span></div></div></section>}
export function Skills(){return <section id="skills" className="section skills-section"><div className="section-heading"><div><p className="eyebrow">02 / Toolkit</p><h2>Things I <em>use.</em></h2></div><p className="section-note">A flexible toolkit for making<br/>good things on the web.</p></div><div className="skill-grid">{Object.entries(portfolio.skills).map(([group,items])=><div className="skill-group" key={group}><div className="skill-group-head"><h3>{group}</h3><span>{String(items.length).padStart(2,'0')} skills</span></div>{items.map((item,i)=><div className="skill" key={item}><span>0{i+1}</span><b>{item}</b><i><u style={{width:`${82-i*9}%`}}/></i></div>)}</div>)}</div></section>}
export function Projects(){return <section id="projects" className="section projects-section"><div className="section-heading"><div><p className="eyebrow">03 / Selected work</p><h2>Built with <em>intent.</em></h2></div><p className="section-note">Scroll sideways to explore<br/>the selected archive →</p></div><div className="projects-scroll">{projectData.map((p,i)=><article className="project-card" key={p.title}><div className="project-art" style={{'--project-color':p.color}}><span>0{(i%9)+1}</span><div className="art-word">{p.title.slice(0,2)}</div><ArrowUpRight/></div><div className="project-info"><p>{p.type}</p><h3>{p.title}</h3><p className="project-text">{p.text}</p><div className="tags">{p.tags.map(t=><span key={t}>{t}</span>)}</div></div></article>)}</div></section>}
export function Timeline({id,label,title,items}){return <section id={id} className="section split timeline-section"><div><p className="eyebrow">{label}</p><h2>{title}</h2></div><div className="timeline">{items.map(item=><div className="timeline-item" key={item[0]}><span className="timeline-date">{item[0]}</span><div><h3>{item[1]}</h3><strong>{item[2]}</strong><p>{item[3]}</p></div></div>)}</div></section>}
export function Contact(){const submit=e=>{e.preventDefault();const f=new FormData(e.currentTarget);window.location.href=`mailto:${portfolio.email}?subject=Hello Alex — let&apos;s work together&body=Name: ${encodeURIComponent(f.get('name'))}%0AEmail: ${encodeURIComponent(f.get('email'))}%0A%0A${encodeURIComponent(f.get('message'))}`};return <section id="contact" className="section contact"><div><p className="eyebrow">06 / Contact</p><h2>Let&apos;s make<br/><em>something.</em></h2><p className="contact-copy">Have a project in mind, or just want to say hello? My inbox is always open.</p><a className="email-link" href={`mailto:${portfolio.email}`}><Mail size={17}/> {portfolio.email}</a></div><form onSubmit={submit}><label>Name<input name="name" required placeholder="Your name"/></label><label>Email<input name="email" type="email" required placeholder="you@example.com"/></label><label>Message<textarea name="message" required rows="4" placeholder="Tell me a little about your project..."/></label><button className="button button--primary" type="submit">Send message <ArrowUpRight size={17}/></button></form></section>}
export function Terminal(){return <section className="terminal-section section"><div className="terminal"><div className="terminal-top"><TerminalIcon size={15}/> alex@studio <span>● ● ●</span></div><div className="terminal-body"><p><b>$</b> whoami</p><p className="cyan">creative developer</p><p><b>$</b> cat /now.txt</p><p className="muted">building things that feel<br/>a little more human.</p><p><b>$</b> <span className="cursor"/></p></div></div></section>}
